name: jackshub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  cupertino_icons: ^0.1.2
  fluro: "^1.4.0"
  auto_size_text: ^2.1.0
  intl: ^0.16.0
  sqflite:
  path_provider:
  flutter_bloc:
  equatable:
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  fonts:
    - family: Hobo
      fonts:
        - asset: lib/assets/fonts/HoboBT.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-Black.ttf
          weight: 900
  assets:
    - lib/assets/images/
